import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypeScript from "eslint-config-next/typescript"

const config = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",

      // React Compiler rules from eslint-config-next 16.
      //
      // set-state-in-effect is enforced: the first-party violations are fixed
      // (use-mobile now uses useSyncExternalStore, breathing-exercise advances
      // its phase inside the timer callback, and daily-tip/motivational-hero
      // no longer pick their content in an effect).
      "react-hooks/set-state-in-effect": "error",

      "react-hooks/purity": "error",
    },
  },
  {
    // Server Components that read the clock while rendering. This rule is a
    // React Compiler rule aimed at client render purity, where calling
    // Date.now() causes hydration mismatches; on the server there is no
    // hydration and reading the clock per request is idiomatic.
    //
    // Each of these is deliberately not statically prerendered, so the value is
    // computed fresh rather than frozen: /app and /dashboard are
    // force-dynamic, and /demo revalidates hourly (its counter was in fact
    // frozen at build time until that was added — see NIK-108).
    //
    // Scoped to these three files rather than app/**, so a new page that reads
    // the clock has to make this decision consciously instead of inheriting an
    // exemption.
    files: ["app/app/page.tsx", "app/dashboard/page.tsx", "app/demo/page.tsx"],
    rules: {
      "react-hooks/purity": "off",
    },
  },
  {
    // Vendored shadcn/ui. These files are regenerated by `shadcn add`, so any
    // in-place fix is silently reverted on the next component update. The
    // violations are a Math.random() skeleton width (sidebar) and a
    // setState-in-effect (carousel), both upstream's code, not ours.
    files: ["components/ui/**"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]

export default config
