import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypeScript from "eslint-config-next/typescript"

const config = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",

      // React Compiler rules from eslint-config-next 16.
      //
      // set-state-in-effect is enforced: the first-party violations are fixed
      // (use-mobile now uses useSyncExternalStore, breathing-exercise advances
      // its phase inside the timer callback, and daily-tip/motivational-hero
      // no longer pick their content in an effect).
      "react-hooks/set-state-in-effect": "error",

      // purity is still a warning for one reason: it fires on Date.now() during
      // render in app/app, app/dashboard and app/demo, which are Server
      // Components. Per-request Date.now() on the server is idiomatic and
      // carries no hydration risk, so the rule is firing outside the context it
      // was written for. The real question there is caching, not purity —
      // Date.now() opts those routes out of static rendering. Left as "warn"
      // pending that decision. See NIK-108.
      "react-hooks/purity": "warn",
    },
  },
  {
    // Vendored shadcn/ui. These files are regenerated by `shadcn add`, so any
    // in-place fix is silently reverted on the next component update. The
    // violations are a Math.random() skeleton width (sidebar) and a
    // setState-in-effect (carousel), both upstream's code, not ours.
    files: ["components/ui/**"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]

export default config
